#!/bin/sh
.git/hooks/ctags >/dev/null 2>&1 &

### lolcommits hook (begin) ###
export LANG="en_GB.UTF-8"
export PATH="/Users/paul/.rvm/rubies/ruby-2.2.3/bin:/usr/local/bin:$PATH"
lolcommits --capture
###  lolcommits hook (end)  ###
