#!/bin/sh
.git/hooks/ctags >/dev/null 2>&1 &

### lolcommits hook (begin) ###
export LANG="en_GB.UTF-8"
export LOLCOMMITS_DELAY=1
lolcommits --capture
###  lolcommits hook (end)  ###
API_KEY=B637jQfgRuS7G47gQmjeKZOuns160kvrHKYgSbD_

# REQUIRED FIELDS - Today's date and commit message
MESSAGE=$(git log -1 HEAD --pretty=format:%s)
DATE_TODAY=$(date +"%Y-%m-%d %H:%M:%S")

# OPTIONAL - Label
LABEL='code commit'

if [[ ${#MESSAGE} -gt 20 ]]; then
  curl --data "key=$API_KEY&highlight_date=$DATE_TODAY&description=$MESSAGE&source=$LABEL" https://www.rescuetime.com/anapi/highlights_post
fi
