#!/bin/sh
.git/hooks/ctags >/dev/null 2>&1 &

# If there's a composer.lock file and Vagrant is install, make sure composer is up to date
[ -e composer.lock ] && [ -e Vagrantfile ] &&  vagrant ssh -c "cd /vagrant; composer install" || true
