---
- hosts: localhost
  tasks:
    - file: src={{ playbook_dir }}/agignore dest=~/.agignore state=link
    - file: src={{ playbook_dir }}/zshrc dest=~/.zshrc state=link force=true
    - file: src={{ playbook_dir }}/ansible.cfg dest=~/.ansible.cfg state=link
    - file: src={{ playbook_dir }}/ssh_config dest=~/.ssh/config state=link
    - file: src={{ playbook_dir }}/asdfrc dest=~/.asdfrc state=link
    - file: path=/etc/ansible state=directory
      become_user: root
      become: true
    - file: src={{ playbook_dir }}/bin/hosts dest=/private/etc/ansible/hosts state=link force=true
      become_user: root
      become: true

    # Give me a tmp directory
    - file: path=~/.tmp state=directory
    
    # Git Template and webhooks for autorunning ctags
    - file: src={{ playbook_dir }}/gitconfig dest=~/.gitconfig state=link

    # tmux attach from Thoughtbot
    - file: src={{ playbook_dir }}/bin/tat dest=/usr/local/bin/tat state=link
      become_user: root
      become: true
    - file: src={{ playbook_dir }}/tmux.conf dest=~/.tmux.conf state=link

    # tmuxinator config directory
    - file: src={{ playbook_dir }}/tmuxinator dest=~/.tmuxinator state=link
  