---
- hosts: localhost
  sudo: no
  tasks:
    - file: src={{ playbook_dir }}/agignore dest=~/.agignore state=link
    - file: src={{ playbook_dir }}/vimrc dest=~/.vimrc state=link
    - file: src={{ playbook_dir }}/zshrc dest=~/.zshrc state=link

    # Give me a tmp directory
    - file: path=~/.tmp state=directory
    
    # Git Template and webhooks for autorunning ctags
    - file: path=~/.git_template state=directory
    - file: path=~/.git_template/hooks state=directory
    
    - file: path={{ playbook_dir }}/git-hooks/ctags state=touch mode=0744
    - file: src={{ playbook_dir }}/git-hooks/ctags dest=~/.git_template/hooks/ctags state=link 

    - file: path={{ playbook_dir }}/git-hooks/post-commit state=touch mode=0744
    - file: src={{ playbook_dir }}/git-hooks/post-commit dest=~/.git_template/hooks/post-commit state=link 
    
    - file: path={{ playbook_dir }}/git-hooks/post-merge state=touch mode=0744
    - file: src={{ playbook_dir }}/git-hooks/post-merge dest=~/.git_template/hooks/post-merge state=link
    
    - file: path={{ playbook_dir }}/git-hooks/post-checkout state=touch mode=0744
    - file: src={{ playbook_dir }}/git-hooks/post-checkout dest=~/.git_template/hooks/post-checkout state=link
    
    - file: path={{ playbook_dir }}/git-hooks/post-rewrite state=touch mode=0744
    - file: src={{ playbook_dir }}/git-hooks/post-rewrite dest=~/.git_template/hooks/post-rewrite state=link 
    
    - file: src={{ playbook_dir }}/gitconfig dest=~/.gitconfig state=link
