---
- hosts: localhost
  sudo: no
  tasks:
    - file: src={{ playbook_dir }}/agignore dest=~/.agignore state=link
    - file: src={{ playbook_dir }}/vimrc dest=~/.vimrc state=link
    - file: src={{ playbook_dir }}/zshrc dest=~/.zshrc state=link
    - file: src={{ playbook_dir }}/jshintrc dest=~/.jshintrc state=absent
    - file: src={{ playbook_dir }}/eslintrc.js dest=~/.eslintrc.js state=link

    # Give me a tmp directory
    - file: path=~/.tmp state=directory
    
    # Git Template and webhooks for autorunning ctags
    - file: path=~/.git_template state=directory
    - file: path=~/.git_template/hooks state=directory
    - file: src={{ playbook_dir }}/git-hooks/ctags dest=~/.git_template/hooks/ctags state=link mode=0744
    - file: src={{ playbook_dir }}/git-hooks/post-commit dest=~/.git_template/hooks/post-commit state=link mode=0744
    - file: src={{ playbook_dir }}/git-hooks/post-merge dest=~/.git_template/hooks/post-merge state=link mode=0744
    - file: src={{ playbook_dir }}/git-hooks/post-checkout dest=~/.git_template/hooks/post-checkout state=link mode=0744
    - file: src={{ playbook_dir }}/git-hooks/post-rewrite dest=~/.git_template/hooks/post-rewrite state=link mode=0744
    - file: src={{ playbook_dir }}/git-hooks/pre-commit dest=~/.git_template/hooks/pre-commit state=link mode=0744
    - file: src={{ playbook_dir }}/gitconfig dest=~/.gitconfig state=link

    # rvm hooks
  
    - file: src={{ playbook_dir }}/rvm-hooks/after_use_show_ruby dest=~/.rvm/hooks/after_use_show_ruby state=link

    # tmux attach from Thoughtbot
    - file: src={{ playbook_dir }}/bin/tat dest=/usr/local/bin/tat state=link
    - file: src={{ playbook_dir }}/tmux.conf dest=~/.tmux.conf state=link
    - shell: tmux source-file ~/.tmux.conf

    - file: dest=~/.vim state=directory
    - file: src={{ playbook_dir }}/UltiSnips dest=~/.vim/UltiSnips state=link

    # tmuxinator config directory
    - file: src={{ playbook_dir }}/tmuxinator dest=~/.tmuxinator state=link
