#! /bin/bash
echo ""
if [ $rvm_ruby_string ]; then
  THE_RUBY_STRING="${Bold}${Red}$rvm_ruby_string${Rst}"
else
  THE_RUBY_STRING="${Bold}${White}default${Rst}"
fi
echo "${Bold}${Green}>>${Rst}  Now using ruby: $THE_RUBY_STRING"
